fix and formatting
leviovan/angoular-todo pull request #1
Opened 2024-08-29 08:52 UTC by leviovan

2024-08-29 11:19 UTC, tamazyanarsen requested changes

2024-08-29 11:19 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.html
> +      <button [ngClass]="{'active':filter==='completed'}" (click)="setFilter('completed')">Сделанные </button>
`filter===''` и остальные сравнения можно вынести в метод `isActiveClass(filter: <тип фильтра>)`

2024-08-29 11:19 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
> +  newTodo:string|null=null
я уже писал про форматирование кода

исправь

2024-08-29 11:19 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
>    setFilter(newFilter:statuses) {
statuses -- название типа?

если да, то типы называются с большой буквы и в единственном числе

Status

почитай style guide по ts https://google.github.io/styleguide/tsguide.html

2024-08-29 11:19 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
>    title:string,
типы стоит вынести в отдельную папку types и сгруппировать по модулю

например, `types/todo.ts`

2024-08-29 11:19 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
> +    this.todos[indexTodo].status= this.todos[indexTodo].status==='active' ? 'completed': "active"
поиск и изменение элемента стоит делать через уникальный идентификатор (поле id внутри каждого элемента)

не стоит использовать порядковые номера (индексы) массива для поиска элемента

2024-08-29 12:12 UTC, merged

2024-08-30 02:46 UTC, tamazyanarsen commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() i!: number;
названия переменных должны быть понятные

никогда не называй переменную одной буквой

любой другой разработчик, который читает твой код, должен сразу понимать, что означает то или иное название свойства/функции

2024-08-30 02:46 UTC, tamazyanarsen commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() i!: number;
убрать в коде все not null assertion `!`

их использование очень опасно

добавь лучше везде дополнительные проверки на undefined, а не просто `!`

2024-08-30 02:46 UTC, tamazyanarsen commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() removeTodo!: (i: number) => void;
не стоит передавать в компонент функцию

в Input лучше передавать примитивы (почитай про типы данных)

или можно передавать массивы, объекты, но не функции

2024-08-30 02:46 UTC, tamazyanarsen commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Output() eventRemoveTodo = new EventEmitter<number>()
общее описание переменной, типа или еще чего-то записывается как суффикс, а не префикс

2024-08-30 02:46 UTC, tamazyanarsen commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  clickout(event: any) {
запрещено использовать тип any

2024-08-30 08:38 UTC, leviovan commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() i!: number;
исправил

2024-08-30 08:38 UTC, leviovan commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() i!: number;
поправил

2024-08-30 08:38 UTC, leviovan commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Input() removeTodo!: (i: number) => void;
Понял в чем была ошибка, исправил

2024-08-30 08:38 UTC, leviovan commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  @Output() eventRemoveTodo = new EventEmitter<number>()
исправил

2024-08-30 08:38 UTC, leviovan commented on src/app/component/list-todo/list-item/list-item.component.ts
> +  clickout(event: any) {
Исправил, поменял на Event