refactor(elements)
leviovan/angoular-todo pull request #4
Opened 2024-08-30 08:49 UTC by leviovan

remove null assertion and type Any
remove @input for function

2024-09-02 09:54 UTC, tamazyanarsen requested changes

2024-09-02 09:54 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
> +  }
а где форматирование кода?

2024-09-02 09:54 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
> +     this.todoService.updateTodo([...this.todos])
зачем лишний пробел?

2024-09-02 09:54 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.ts
> +    this.todoService.updateTodo([...newTodos])
работа со списком должна быть в сервисе

изменение, удаление, создание и чтение

всё через сервис

2024-09-03 03:18 UTC, tamazyanarsen commented on src/app/component/todo/todo.component.html
> +        <button (click)="addTodo(newTodo!)">Добавить дело</button>
мы же договаривались, что не стоит использовать `!`

2024-09-03 03:18 UTC, tamazyanarsen commented on src/app/services/todo.service.ts
> +      this.id = this.id + 1;
id для каждого объекта todo создается на месте
это должно быть что-то уникальное, а не просто порядковый номер

например, Date.now(), в реальных проектах используют uuid

2024-09-03 03:18 UTC, tamazyanarsen commented on src/app/services/todo.service.ts
>    updateTodo(newState: Todo[]) {
метод update должен обновлять конкретный todo, а не сразу весь массив

2024-09-03 03:18 UTC, tamazyanarsen commented on src/app/services/todo.service.ts
> +    const indexTodo = this.todos.value.map(t => t.id).indexOf(id)
замени на `findIndex`, но лучше сделать через `filter`

оставляем все элементы, кроме того, где совпадает id

2024-09-03 07:59 UTC, leviovan commented on src/app/component/todo/todo.component.html
> +        <button (click)="addTodo(newTodo!)">Добавить дело</button>
Исправил, плохая привычка

2024-09-03 08:00 UTC, leviovan commented on src/app/services/todo.service.ts
>    updateTodo(newState: Todo[]) {
А он даже не использовался, убрал

2024-09-03 08:00 UTC, leviovan commented on src/app/services/todo.service.ts
> +      this.id = this.id + 1;
Я знаю, что id уникальное должно быть, и создал такой способ, который при создании туду создавал уникальный номер, щас изменю на Date.now

2024-09-03 08:00 UTC, leviovan commented on src/app/services/todo.service.ts
> +    const indexTodo = this.todos.value.map(t => t.id).indexOf(id)
Хотел с фильтром сналало, но почему-то сделал так, поправил

2024-09-04 04:17 UTC, merged