My new branch
leviovan/angoular-todo pull request #6
Opened 2024-09-06 09:44 UTC by leviovan

2024-09-09 09:34 UTC, tamazyanarsen commented on src/app/app.module.ts
> +import { MyTodoLibModule } from "../../projects/my-todo-lib/src/lib/my-todo-lib.module";
здесь должен быть не относительный путь, а имя библиотеки

2024-09-09 10:16 UTC, leviovan commented on src/app/app.module.ts
> +import { MyTodoLibModule } from "../../projects/my-todo-lib/src/lib/my-todo-lib.module";
поправил и залил

2024-09-10 11:25 UTC, tamazyanarsen requested changes

2024-09-10 11:25 UTC, tamazyanarsen commented on projects/my-todo-lib/src/lib/my-todo-lib.service.ts
> +}
зачем нужен пустой сервис?

2024-09-10 17:17 UTC, leviovan commented on projects/my-todo-lib/src/lib/my-todo-lib.service.ts
> +}
Не зачем, скорее всего создался при создании либы, удалил и удалил ненужные импорты

2024-09-11 11:24 UTC, merged